<a href="https://colab.research.google.com/github/AlinaSabitova/Python_Programming/blob/main/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

№ 4.2.1

Рассчитать значение f при заданном значении вещественного числа x:

![image.png]()

При выводе на экран оставьте 2 знака после запятой.

In [ ]:
# Задание task_04_02_01.

# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


x = float(input("Введите число x:"))

if x >= 0:
    f = x**(1/2) + x**2
else:
    f = 1/x

print("f=", round(f, 2))

# --------------
# Пример вывода:
#
# Введите число x: -10
# f = -0.10

# Введите число x: 0
# f = 0.00

# Введите число x: 10
# f = 103.16

Введите число x:10
f= 103.16

№ 4.2.2

Определите максимальное и минимальное значения из двух различных целых чисел.

In [ ]:
# Задание task_04_02_02.

# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


a1 = int(input("Введите первое число:"))
a2 = int(input("Введите второе число:"))

if a1 > a2:
  print("Максимум:", a1, "Минимум:", a2)
else:
  print("Максимум:", a2, "Минимум:", a1)

# --------------
# Пример вывода:
#
# Введите первое число: 1
# Введите второе число: 2
# Максимум: 2, минимум: 1

# Введите первое число: 5
# Введите второе число: 5
# Максимум: 5, минимум: 5

# Введите первое число: 100
# Введите второе число: -1
# Максимум: 100, минимум: -1

Введите первое число:100
Введите второе число:-1
Максимум: 100 Минимум: -1

№ 4.2.3

Вася пытается высунуть голову в форточку размерами a и b см. Приняв условно, что его голова - круглая диаметром d см, определите, сможет ли Вася сделать это. Для прохождения головы в форточку необходим зазор в 1 см. с каждой стороны.

Все величины - целые числа.

In [ ]:
# Задание task_04_02_03.

# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


a = int(input("Ширина форточки:"))
b = int(input("Высота форточки:"))
d = int(input("Диаметр головы:"))

if (a or b or d) < 0:
  print("Проверьте ввод")
else:
    if d < a and d < b:
      fix = 1  
      print("Да")
    else:
      print("Нет")   

# --------------
# Пример вывода:
#
# Ширина форточки: 5
# Высота форточки: 6
# Диаметр головы: 6
# Нет

# Ширина форточки: 6
# Высота форточки: 7
# Диаметр головы: 4
# Да

Ширина форточки:6
Высота форточки:7
Диаметр головы:4
Да

№ 4.2.4

Известны год и номер месяца сегодняшнего дня, а также год и номер месяца рождения человека (нумерация месяцев с 1: январь - 1 и т.д.). Определите возраст человека (число полных лет).

In [ ]:
# Задание task_04_02_04.

# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


year_today = int(input("Введите текущий год:"))
month_today = int(input("Введите текущий месяц:"))

year = int(input("Введите год рождения:"))
month = int(input("Введите месяц рождения:"))

if month_today >= month:
    age = year_today-year 
else:
    age = year_today-year-1
    
print("Число полных лет: ", age)

# --------------
# Пример вывода:
#
# Введите текущий год: 2017
# Введите текущий месяц: 5
# Введите год рождения: 2000
# Введите месяц рождения: 1
# Число полных лет:  17
#
# Введите текущий год: 2015
# Введите текущий месяц: 6
# Введите год рождения: 2010
# Введите месяц рождения: 8
# Число полных лет:  4
#
# Введите текущий год: 2020
# Введите текущий месяц: 5
# Введите год рождения: 2000
# Введите месяц рождения: 5
# Число полных лет:  20

Введите текущий год:2020
Введите текущий месяц:5
Введите год рождения:2000
Введите месяц рождения:5
Число полных лет:  20

№ 4.2.5

Дана точка с целыми ненулевыми координатами (x;y). Определить номер четверти координатной плоскости, которой она принадлежит.

In [ ]:
# Задание task_04_02_05.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


x = int(input("Введите координату x:"))
y = int(input("Введите координату y:"))

if x > 0 and y > 0:
    print("1-я четверть")
elif x < 0 and y > 0:
    print("2-я четверть")
elif x < 0 and y < 0:
    print("3-я четверть")
else:
    print("4-я четверть")

# --------------
# Пример вывода:
#
# Введите координату x: 5
# Введите координату y: 7
# 1-я четверть

Введите координату x:5
Введите координату y:7
1-я четверть

№ 4.2.6

Даны вещественные числа a, b, c (a≠0).

Решите уравнение ax2+bx+c=0. При выводе значений оставьте 1 знак после запятой.

In [ ]:
# Задание task_04_02_06.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


a = float(input("a="))
b = float(input("b="))
c = float(input("c="))

d = ((b**2)-(4*a*c))

if d < 0: 
  print("Нет решений")
elif d == 0:
  x = -1*b/(2*a)
  print("x=", x)
elif d > 0:
  x1 = (((-1*b)-(d**(1/2)))/2*a) 
  x2 = (((-1*b)+(d**(1/2)))/2*a)
  print("x1=", round(x1, 1), "x2=", round(x2, 1)) 

# --------------
# Пример вывода:
#
# a = 1
# b = 2
# c = 3
# Решений нет
#
# a = 1
# b = 2
# c = 1
# x = -1.0
#
# a = 1
# b = 3
# c = -4
# x1 = -4.0, x2 = 1.0

a=1
b=3
c=-4
x1= -4.0 x2= 1.0

№ 4.2.7

Дана непустая последовательность целых чисел, оканчивающаяся нулем. Найти сумму и количество введенных чисел.

In [ ]:
# Задание task_04_02_07.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


nums_sum = 0  
nums_count = 0  

x = int(input("Введите число:"))
a = []
while x != 0:
    nums_count = nums_count+1
    a.append(x)
    nums_sum = nums_sum+x
    x = int(input("Введите новое число:"))

print("Сумма=", nums_sum)
print("Количество=", nums_count)

# --------------
# Пример вывода:
#
# Введите 1-е число: 1
# Введите 2-е число: 2
# Введите 3-е число: 3
# Введите 4-е число: 4
# Введите 5-е число: 0
# Сумма = 10
# Количество = 4
#
# Введите 1-е число: 0
# Сумма = 0
# Количество = 0

Введите число:0
Сумма= 0
Количество= 0

№ 4.2.8

Дано число n. Из чисел 0,5,10,15,20,25,... напечатать те, которые не превышают n.

In [ ]:
# Задание task_04_02_08.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


n = int(input("n="))

q = 0
m = list()
m.append(q)

while q <= n:
  q = q+5
  m.append(q)
m.pop()
print(m)



# --------------
# Пример вывода:
#
# n = 0
# 0
#
# n = 10
# 0
# 5
# 10
#
# n = 12
# 0
# 5
# 10

n=12
[0, 5, 10]

№ 4.2.9

Дано вещественное число a. Найдите наименьшее натуральное n, для которого верно:

![image.png]()

In [ ]:
# Задание task_04_02_09.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


a = float(input("a="))

n = 1
x_sum = list()
x_sum.append(n)

while sum(x_sum) <= a:
  n = n+1
  g = 1/n
  x_sum.append(g)

print("n=", n)
# --------------
# Пример вывода:
#
# a = 1.5
# n = 3
#
# a = 2
# n = 4

a=2
n= 4

№ 4.2.10

Дано натуральное число. Определите сумму и количество его цифр.

In [ ]:
# Задание task_04_02_10.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


n = list(map(int,input("n=")))

n_sum = sum(n)
n_count = len(n)

print("Cумма=", n_sum)
print("Количество=", n_count)

# --------------
# Пример вывода:
#
# n = 12345
# Сумма = 15
# Количество = 5

n=12345
Cумма= 15
Количество= 5

№ 4.2.13

Для введенных с клавиатуры положительных целых чисел a и b (a≤b) определите:

сумму всех целых чисел от a до b;

произведение всех целых чисел от a до b;

среднее арифметическое всех целых чисел от a до b;

среднее геометрическое нечетных чисел от a до b.

Отрезок поиска включает сами числа a и b. При выводе вещественных результатов оставьте два знака после запятой.

In [ ]:
# Задание task_04_02_13.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


a = int(input("a="))
b = int(input("b="))
n = list(range(a, b+1, 1))

n_sum = sum(n)

n_mult = 1
a = 1
while a < len(n):
    n_mult = n_mult*n[a]
    a += 1

n_avg = n_sum/len(n)

print("Сумма =", n_sum)
print("Произведение =", n_mult)
print("Среднее арифметическое =", round(n_avg, 2))

b = 1
m = 0
n_avg_geom = 1
while b<len(n):
    if n[b]%2 == 1:
        n_avg_geom = n_avg_geom*n[b]
        b += 2
        m += 1
    else:
        b += 1

m += 1
n_avg_geom = round((n_avg_geom**(1/m)), 2)

print("Среднее геометрическое нечетных чисел =", n_avg_geom)

# --------------
# Пример вывода:
#
# a = 1
# b = 5
# Сумма = 15
# Произведение = 120
# Среднее арифметическое = 3.00
# Среднее геометрическое нечетных чисел = 2.47

a=1
b=5
Сумма = 15
Произведение = 120
Среднее арифметическое = 3.0
Среднее геометрическое нечетных чисел = 2.47

№ 4.2.14

Начав тренировки, лыжник в первый день пробежал s км. (s>0, вещественное число). Каждый следующий день он увеличивал пробег на p % (0<p≤100, вещественное число) от пробега предыдущего дня. Определите:

пробег лыжника за второй, третий, …, десятый день тренировок;

какой суммарный путь он пробежал за первые 10 дней тренировок.

При выводе вещественных результатов оставьте один знак после запятой.

In [ ]:
# Задание task_04_02_14.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


s = float(input("Пробег за 1-ый день (км.) ="))
p = float(input("На сколько увеличивает пробег (%) ="))

m = list()
m.append(s)

day = 1
for i in range(9):
    s = ((s*(p/100))+s)+0.0001
    day += 1
    m.append(s)
    print("Пробег за", day,"день: ", round(s, 1), "км.")

total = sum(m)

print("Суммарный пробег: ", round(total,1))


# --------------
# Пример вывода:
#
# Пробег за 1-й день (км.) = 5
# На сколько увеличивает пробег (%) = 10
# Пробег за 2-й день: 5.5 км.
# Пробег за 3-й день: 6.1 км.
# Пробег за 4-й день: 6.7 км.
# Пробег за 5-й день: 7.3 км.
# Пробег за 6-й день: 8.1 км.
# Пробег за 7-й день: 8.9 км.
# Пробег за 8-й день: 9.7 км.
# Пробег за 9-й день: 10.7 км.
# Пробег за 10-й день: 11.8 км.
# Суммарный пробег: 79.7 км.

Пробег за 1-ый день (км.) =5
На сколько увеличивает пробег (%) =10
Пробег за 2 день:  5.5 км.
Пробег за 3 день:  6.1 км.
Пробег за 4 день:  6.7 км.
Пробег за 5 день:  7.3 км.
Пробег за 6 день:  8.1 км.
Пробег за 7 день:  8.9 км.
Пробег за 8 день:  9.7 км.
Пробег за 9 день:  10.7 км.
Пробег за 10 день:  11.8 км.
Суммарный пробег:  79.7

№ 4.2.15

Известна масса каждого предмета в кг., загружаемого в грузовик. Определить, возможна ли перевозка груза, если грузоподъемность грузовика равна p кг.

In [ ]:
# Задание task_04_02_15.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


p = int(input("Грузоподъемность грузовика (кг.) ="))
n = int(input("Количество предметов ="))

m = list()
for i in range(n):
  weight = int(input("Введите массу предмета (кг.): "))
  m.append(weight)

if sum(m)>=p: 
    print("Нет")
else:
    print("Да")


# --------------
# Пример вывода:
#
# Грузоподъемность грузовика (кг.) = 10
# Количество предметов = 2
# Масса 1-го предмета (кг.) = 3
# Масса 2-го предмета (кг.) = 3
# Да

Грузоподъемность грузовика (кг.) =10
Количество предметов =2
Введите массу предмета (кг.): 3
Введите массу предмета (кг.): 3
Да

№ 4.2.16

В области несколько районов. Заданы площади, засеваемые пшеницей (га.), и средняя урожайность (ц/га) в каждом районе.

Определите количество пшеницы, собранное по области. При выводе вещественных результатов оставьте один знак после запятой.

In [ ]:
# Задание task_04_02_16.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru

n = int(input("Количество районов ="))

number = list()

for i in range(n):
  s = float(input("Площадь района (га) ="))
  p = float(input("Урожайность в районе (ц.га) ="))
  harvest = s*p
  number.append(harvest)

total = sum(number)

print("Собрано пшеницы =", round(total, 1))

# --------------
# Пример вывода:
#
# Количество районов = 3
# Площадь 1-го района (га) = 4
# Урожайность в 1-м районе (ц/га.) = 2
# Площадь 2-го района (га) = 7
# Урожайность в 2-м районе (ц/га.) = 3
# Площадь 3-го района (га) = 9
# Урожайность в 3-м районе (ц/га.) = 4
# Собрано пшеницы: 65.0 ц.

Количество районов =3
Площадь района (га) =4
Урожайность в районе (ц.га) =2
Площадь района (га) =7
Урожайность в районе (ц.га) =3
Площадь района (га) =9
Урожайность в районе (ц.га) =4
Собрано пшеницы = 65.0

№ 4.2.17

Решите задачу № 4.2.7, организовав бесконечный цикл, который бы прерывался при выполнении условия, используя оператор break.

In [ ]:
# Задание task_04_02_17.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


nums_sum = 0  # сумма
nums_count = 0  # количество 

x = int(input("Введите число:"))
a = []
while x != 0:
    nums_count = nums_count+1
    a.append(x)
    nums_sum = nums_sum+x
    x = int(input("Введите новое число:"))
    if x == 0:  
      break

print("Сумма=", nums_sum)
print("Количество=", nums_count)

# --------------
# Пример вывода:
#
# Введите 1-е число: 1
# Введите 2-е число: 2
# Введите 3-е число: 3
# Введите 4-е число: 4
# Введите 5-е число: 0
# Сумма = 10
# Количество = 4
#
# Введите 1-е число: 0
# Сумма = 0
# Количество = 0

Введите число:1
Введите новое число:2
Введите новое число:3
Введите новое число:4
Введите новое число:0
Сумма= 10
Количество= 4

№ 4.2.18

Предложение, введенное с клавиатуры, содержит слова из гласных и согласных букв кириллицы (регистр может быть различный), а также пробелы.

Определите количество гласных и согласных букв в предложении. Для пропуска пробелов используйте оператор continue.

In [ ]:
# Задание task_04_02_18.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


sentence =input("Введите предложение:")

count_gl = 0  # Кол-во гласных
count_sogl = 0  # Кол-во согласных

for i in sentence:
  letter = i.lower()
  if letter == "а" or letter == "е" or letter == "ё" or letter == "и" or\
     letter == "о" or letter == "у" or letter == "ы" or letter == "э" or\
     letter == "ю" or letter == "я":
     count_gl += 1
  else: 
     count_sogl += 1
f1 = "гласных -"
f2 = "согласных -"
print('Кол-во букв в предложении: ', "{} {}, {} {}".format(f1, count_gl, f2, count_sogl))
# --------------
# Пример вывода:
#
# Введите предложение: Программирование
# Кол-во букв в предложении: гласных - 7, согласных - 9

Введите предложение:Программирование
Кол-во букв в предложении:  гласных - 7, согласных - 9

№ 4.2.19

Выведите на экран (в строку) все целые числа от a до b, кратные некоторому числу c.

In [ ]:
# Задание task_04_02_19.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


a = int(input("a ="))
b = int(input("b ="))
c = int(input("c ="))

numbers = list()

for i in range(a, b+1, 1):
  if i%c == 0:
    numbers.append(i)
  else:
    i += 1

print(numbers)

# --------------
# Пример вывода:
#
# a = 1
# b = 10
# c = 2
# 2 4 6 8 10

a =1
b =10
c =2
[2, 4, 6, 8, 10]

№ 4.2.20

Выведите на экран (в строку) все трехзначные натуральные числа, сумма цифр которых равна целому числу n (0<n≤27).

In [ ]:
# Задание task_04_02_20.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


n = int(input("n ="))

for i in range(100, 1000):
  f = sum(int(q) for q in str(i)) 
  if f == n:
        print(i, end=" ")

# --------------
# Пример вывода:
#
# n = 3
# 102 111 120 201 210 300

n =3
102 111 120 201 210 300

№ 4.2.21

Известно количество учеников в классе и их рост (см.); рост мальчиков условно задан отрицательными числами. Определите средний рост мальчиков и средний рост девочек.

При выводе вещественных результатов оставьте один знак после запятой.

In [ ]:
# Задание task_04_02_21.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


n = int(input("n ="))

a = 0
b = 0
c = 0
d = 0

for i in range(n):
  r = int(input("Рост ученика ="))
  if r < 0:
    a += 1
    b -= r
  else:
    c += r


r_sr_m = b/a
r_sr_d = c/(n-a)


print("Средний рост мальчиков: {:.1f}".format(r_sr_m))
print("Средний рост девочек: {:.1f}".format(r_sr_d))

# --------------
# Пример вывода:
#
# n = 5
# Рост 1-го ученика = 150
# Рост 2-го ученика = -150
# Рост 3-го ученика = 160
# Рост 4-го ученика = 170
# Рост 5-го ученика = 180
# Средний рост мальчиков: 150.0
# Средний рост девочек: 165.0

n =5
Рост ученика =150
Рост ученика =-150
Рост ученика =160
Рост ученика =170
Рост ученика =180
Средний рост мальчиков: 150.0
Средний рост девочек: 165.0

№ 4.2.22

Даны n вещественных чисел. Определите максимальное и минимальное из них.

При выводе вещественных результатов оставьте два знака после запятой.

In [ ]:
# Задание task_04_02_22.
#
# Выполнил: Сабитова А.Б.
# Группа: Адеу-221
# E-mail: alisab1105@yandex.ru


n = int(input("n ="))

m = list()

for i in range(n):
  a = float(input("Число ="))
  m.append(a)
  
a_max = max(m)
a_min = min(m)

print("Максимум: {:.2f}".format(a_max))
print("Минимум: {:.2f}".format(a_min))

# --------------
# Пример вывода:
#
# n = 4
# 1-е число = 6.2
# 2-е число = 3.8
# 3-е число = 1.1
# 4-е число = 9.66
# Максимум: 9.66
# Минимум: 1.10

n =4
Число =6.2
Число =3.8
Число =1.1
Число =9.66
Максимум: 9.66
Минимум: 1.10